name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

      fail-fast: false

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, simplexml, json
          coverage: none

      - run: composer install --no-progress --prefer-dist
      - run: composer tests
      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: tests/**/output
